server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:        # 如果有密码就填上
      database: 15
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.seckill.backend.domain
  configuration:
    map-underscore-to-camel-case: true
